# Generated by Django 3.2.8 on 2021-12-29 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='a@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='bro', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=134235554, max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(default='extra', upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facmanage.category'),
        ),
    ]
