# Generated by Django 3.2.8 on 2021-12-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facmanage', '0004_auto_20211230_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_of_order',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/products/'),
        ),
    ]
