# Generated by Django 3.2.8 on 2021-12-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facmanage', '0005_auto_20211230_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='price',
        ),
    ]
