# Generated by Django 3.2.8 on 2021-12-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facmanage', '0006_rename_amount_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
