# Generated by Django 3.2.8 on 2021-12-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facmanage', '0007_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
